version: "3.8"

services:
  apache: 
    build: 
      context: "./apache/"
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./web/:/var/www/html/
    env_file:
      - .env
  
  mysql:
    build:
      context: "./mysql"
    env_file:
      - .env
