version: "3.8"

services:
  apache: 
    build: 
      context: "./apache/"
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./web/:/var/www/html/

  php:
    build:
      context: "./php"
  
  mysql:
    build:
      context: "./mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=Privz3toGesl0
