version: "3.8"

services:
  apache: 
    build: 
      context: "./apache/"
    depends_on:
      - mysql
    expose:
      - 80
    volumes:
      - ./web/:/var/www/html/
    env_file:
      - .env
  
  mysql:
    build:
      context: "./mysql"
    expose:
      - 3306
    env_file:
      - .env

  phpmyadmin:
    build:
      context: "./phpmyadmin" 
    depends_on:
      - mysql
    expose:
      - 80
    env_file:
      - .env
    environment:
      - PMA_HOST=mysql

  proxy:
    build:
      context: "./proxy"
    depends_on:
      - apache
      - phpmyadmin
    ports:
      - "8888:8888"
      - "8889:8889"
    extra_hosts:
      - "apache.local:127.0.0.1"
      - "phpmyadmin.local:127.0.0.1"